addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev
after_success:
  - npm run coveralls
before_install:
  - git config --global user.name travis
  - git config --global user.email travis@locahost
install:
  - BUILD_ONLY=true npm install
language: node_js
node_js:
  - '4.4'
  - 'stable'
os:
  - linux
sudo: false
