addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - libc6-dev
after_success:
  - npm run coveralls
before_install:
  - export CC="gcc-4.9"
  - export CXX="g++-4.9"
  - git config --global user.name travis
  - git config --global user.email travis@locahost
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - '4.4'
  - 'stable'
os:
  - linux
sudo: false
